import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link
          href="https://www.youtube.com/watch?v=xvFZjo5PgG0"
          target="_blank"
        >
          <div style={{ fontSize: "10rem" }}>Roll</div>
        </Link>
      </main>
    </>
  );
}
